version: '3.8'

services:
  comprala_backend:
    container_name: comprala_backend
    build: ./comprala-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./comprala-backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    tty: true

  # comprala_frontend:
  #   container_name: comprala_frontend
  #   build: ./comprala-frontend
  #   volumes:
  #     - ./comprala-frontend:/app
  #     - /app/node_modules
  #   expose:
  #     - 3000
  #   tty: true
  #   command: yarn dev
  
  # nginx:
  #   container_name: nginx
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - comprala_backend
  #     - comprala_frontend
  #   tty: true

  postgres:
    container_name: comprala_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: comprala
      POSTGRES_DB: comprala
    ports:
      - 5432:5432
    volumes:
      - .dbdata:/var/lib/postgresql

  mail_hog:
    container_name: comprala_mailhog
    image: mailhog/mailhog
    ports:
      - "8025:8025"


  # pg_admin:
  #   container_name: comprala_pgadmin
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - 5050:80
  #   volumes:
  #     - .pgadmindata:/var/lib/pgadmin
  #   depends_on:
  #     - postgres

