# Generated by Django 4.2.1 on 2023-06-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='IbDQsqzIImFlT4bWO3u9S6', max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
