# Generated by Django 4.2.1 on 2023-06-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_passwordresettoken_token_delete_customtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='compralauser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='TBOcZMbIJePuPztt4JrLHK', max_length=255, unique=True),
        ),
    ]
